# The pubspec file
# https://dart.dev/tools/pub/pubspec

name: kite
version: 1.5.2+34

description: "上应小风筝 APP，基于 Flutter。"

homepage: https://github.com/SIT-kite/kite-app
repository: https://github.com/SIT-kite/kite-app
issue_tracker: https://github.com/SIT-kite/kite-app/issues
documentation: https://github.com/SIT-kite/kite-app#readme

publish_to: none
environment: { sdk: ">=2.19.0 <3.0.0", flutter: ^3.7.2 }

# ------------------------------------------------------------------------------

# View pub packages at: https://pub.dev/packages/{{package_name}}
#               mirror: https://pub.flutter-io.cn/packages/{{package_name}}

dependencies:
  flutter: { sdk: flutter }

  device_info_plus: ^7.0.0
  # I18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # i18n & l10n
  # Basic
  logger: ^1.1.0 # logger
  catcher: ^0.7.0 # Error handling
  path_provider: ^2.0.12 # Path

  # String and charset
  format: ^1.1.1 # String formatting, upgradable
  enough_convert: ^1.6.0 # Character encoding

  # Cryptography
  encrypt: ^5.0.1 # Encryption (AES)
  crypto: ^3.0.1 # Hash (MD5)
  uuid: ^3.0.5 # UUID generator

  # File format
  ical: ^0.2.2 # iCalendar file generator
  json_serializable: ^6.6.1 # JSON
  json_annotation: ^4.8.0 # JSON code generation
  beautiful_soup_dart: ^0.3.0 # HTML parser

  # hive (key-value database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dio (http client)
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0

  # WebView and browser related
  webview_flutter: ^4.0.2
  fk_user_agent: ^2.1.0
  flutter_widget_from_html: ^0.10.0

  # Email
  enough_mail: ^2.1.1
  enough_mail_html: ^2.0.0

  # Settings
  app_settings: ^4.2.0
  flutter_settings_screens: ^0.3.3-null-safety+2

  # Platform
  permission_handler: ^10.2.0 # Android / iOS / Windows Permission
  quick_actions: ^1.0.1 # Android / iOS Home screen quick actions
  device_display_brightness: ^0.0.6 # Android / iOS screen brightness

  # Open with other APP/programs
  open_filex: ^4.3.2 # Open files
  url_launcher: ^6.1.9 # Open URLs
  image_picker: ^0.8.6+1 # Open Android / iOS system image picker
  file_picker: ^5.2.5 # Open system file picker

  # UI
  flash: ^2.0.5
  fl_chart: ^0.60.0
  text_scroll: ^0.1.2
  grouped_list: ^5.1.2
  pull_to_refresh: ^2.0.0
  dynamic_color_theme: ^2.0.0
  geopattern_flutter: { git: { url: https://github.com/SIT-kite/geopattern } }
  flutter_svg: ^2.0.0+1
  flutter_screenutil: ^5.6.1 # Screen adaptation
  flutter_native_splash: ^2.1.1 # Splash screen, upgradable
  flutter_platform_widgets: ^3.0.0 # Platform aware widgets
  flutter_weather_bg_null_safety: ^1.0.0 # Weather background
  audioplayers: ^3.0.1 # audio player
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  photo_view: ^0.14.0
  animated_button_bar: ^0.0.2

  # Utils
  version: ^3.0.2 # Version comparison
  flutter_phoenix: ^1.1.0 # Restart app
  package_info_plus: ^3.0.3 # Get package info (version)
  universal_platform: ^1.0.0+1 # dart.io.Platform API for Web
  check_vpn_connection: ^0.0.2 # Check VPN connection status
  synchronized: ^3.0.0+2 # lock
  stack_trace: ^1.11.0 # parse stacktrace

  # Desktop support
  window_manager: ^0.3.0
  flutter_html: ^3.0.0-alpha.6
  vibration: ^1.7.6
  animations: ^2.0.7
  rettulf: 0.0.7
  tuple: ^2.0.1
  auto_animated: ^3.1.0
  markdown: ^6.0.1
  event_bus: ^2.0.0
  collection: ^1.17.0
  flutter_shake_animated: ^0.0.5
  rnd: ^0.2.0
  animated_size_and_fade: ^3.0.1
  unicons: ^2.1.0
  loading_animation_widget: ^1.2.0+4
  connectivity_plus: ^3.0.3
  modal_bottom_sheet: ^3.0.0-pre
  msh_checkbox: ^2.0.0
  animated_toggle_switch: ^0.6.1
  quiver: ^3.2.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  hive_generator: ^2.0.0

# ------------------------------------------------------------------------------

flutter:
  uses-material-design: true
  # For i18n
  generate: true
  fonts:
    # Iconfont for ywb.sit.edu.cn
    # For office module. So I named it office_iconfont.
    - family: office_iconfont
      fonts: [{ asset: assets/fonts/office_iconfont.ttf }]

    # Good night module
    - family: calligraphy
      fonts: [{ asset: assets/fonts/calligraphy.ttf }]

  assets:
    - assets/
    - assets/common/
    - assets/home/
    - assets/welcome/
    - assets/connectivity/
    - assets/report_temp/
    - assets/fonts/
    - assets/weather/
    - assets/wiki/
    - assets/library/
    - assets/timetable/
    - assets/course/
    - assets/night/
    - assets/game/
    - assets/game/tetris/
    - assets/edu_email/
    - assets/freshman/
    # Prompt sound.
    - assets/game/step.mp3
    - assets/roomlist.json
    - assets/webview/

# See: https://pub.flutter-io.cn/packages/flutter_native_splash
flutter_native_splash:
  fullscreen: true
  color: "#FFFFFF"
  image: assets/icon.png
  # background_image: 'assets/background.png'
flutter_intl:
  enabled: true
