# AppId 的值唯一标识此应用。
# 不要在其他应用的安装程序中使用相同的 AppId 值。
app_id: 5B599538-42B1-4826-A479-AF079F21A65F
publisher: SIT-kite
publisher_url: https://github.com/SIT-kite/kite-app
display_name: Kite
create_desktop_icon: true
setup_icon_file: assets/icon.png
install_dir_name: Sit Kite
locales:
  - en
  - zh
