name: KiteApp

on:
  push:
  pull_request: { branches: [ master ] }

jobs:

  # flutter pub get + flutter analyze
  prebuild:
    runs-on: ubuntu-latest
    # case-insensitive
    if: ${{ !contains(github.event.head_commit.message,'[NoCI]') }}
    steps:

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          channel: stable
          cache: true

      - name: 📌 Restore pub cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }} # use ${{ hashFiles('pubspec.lock') }} when available
          restore-keys: |
            pub-${{ github.ref }}-
            pub-

      - name: 📌 Flutter Code Generate
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter pub run flutter_native_splash:create

      - name: 📌 Cache pub
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }}

      - name: 📌 Cache Workspace
        uses: actions/cache@v3
        with:
          path: |
            lib/
          key: app-${{ github.ref }}-${{ github.sha }}


  ######################
  # Android
  #
  build-Android:
    needs: prebuild
    runs-on: ubuntu-latest
    if: github.repository == 'SIT-kite/kite-app'
    steps:

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          channel: stable
          cache: true

      - name: 📌 Restore pub cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }}

      - name: 📌 Restore Workspace
        uses: actions/cache@v3
        with:
          path: |
            lib/
          key: app-${{ github.ref }}-${{ github.sha }}

      - name: 🏗️ Build Apk (arm64,android-x64)
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build apk --split-per-abi --target-platform android-arm64,android-x64,android-arm

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.APK_SIGN_JKS_BASE64 }}
          alias: ${{ secrets.APK_SIGN_ALIAS }}
          keyStorePassword: ${{ secrets.APK_SIGN_PASS }}

      - name: 📌 Cache Build
        uses: actions/cache@v3
        with:
          path: build/
          key: apk-${{ github.ref }}-${{ github.sha }}

  ######################
  # iOS
  #
  build-iOS:
    # TODO: update to macos-12
    runs-on: macos-latest
    needs: prebuild
    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          # TODO: Fix `Xcode 14 is not supported`
          # xcode-version: '14.0.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          channel: stable
          cache: true

      - name: 📌 Restore pub cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }}

      - name: 📌 Restore Workspace
        uses: actions/cache@v3
        with:
          path: |
            lib/
          key: app-${{ github.ref }}-${{ github.sha }}

      - name: 🏗️ Build iOS
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build ios --no-codesign

  build-Windows:
    runs-on: windows-latest
    needs: prebuild
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          channel: stable
          cache: true

      - name: 🏗️ Build Windows
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build windows

      - name: Upload Windows build file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-windows-x86_64.zip
          path: build/windows/runner/Release

  ######################
  # macOS
  #
  build-macOS:
    runs-on: macos-latest
    needs: prebuild
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
          channel: stable
          cache: true
      # Building
      - name: 🏗️ Build macOS
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build macos --release
      # Signing
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          echo "Create Keychain"
          security create-keychain -p SIT_KITE_PWD build.keychain
          echo "Assign to Login Keychain"
          security default-keychain -s build.keychain
          echo "Unlock the Login Keychain"
          security unlock-keychain -p SIT_KITE_PWD build.keychain
          echo "Import certificate"
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          echo "Set Key Partition"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k SIT_KITE_PWD build.keychain
          echo "Sign the app"
          /usr/bin/codesign --force --deep -s MJGX7ZZ3AG ./$MACOS_APP_RELEASE_PATH/上应小风筝.app

      - name: Upload macOS File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-macos.zip
          path: ./$MACOS_APP_RELEASE_PATH/上应小风筝.app
  ######################
  # Linux
  #
  build-Linux:
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - uses: nelonoel/branch-name@v1.0.1

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: 🏗️ Build Linux
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build linux

      - name: Upload linux build File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-linux-x86_64.zip
          path: build/linux/x64/release/bundle

  # Upload apk
  upload:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: |
      github.ref == 'refs/heads/master' &&
      github.repository == 'SIT-kite/kite-app'
    needs:
      - build-Android
    steps:

      - uses: nelonoel/branch-name@v1.0.1

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with: { length: 7 }

      - name: 📌 Get apk from cache
        uses: actions/cache@v3
        with:
          path: build/
          key: apk-${{ github.ref }}-${{ github.sha }}

      - name: ✏️ Rename apk file
        run: |
          cd build/app/outputs/flutter-apk/
          mv app-armeabi-v7a-release-signed.apk ${{ env.BRANCH_NAME }}-${{ env.SHA }}-armeabi-v7a-release-signed.apk
          mv app-arm64-v8a-release-signed.apk ${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          mv app-x86_64-release-signed.apk ${{ env.BRANCH_NAME }}-${{ env.SHA }}-x86_64-release-signed.apk


      - name: Upload android-x86_64 apk artifact File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-x86_64-release-signed.apk
          path: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-x86_64-release-signed.apk

      - name: Upload android-armeabi-v7a apk artifact File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-armeabi-v7a-release-signed.apk
          path: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-armeabi-v7a-release-signed.apk

      - name: Upload android-arm64-v8a apk artifact File
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          path: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk


      - name: 🤖 Upload apk by bot
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-x86_64-release-signed.apk
          message: "🚀 Android x86_64 Apk Build by Github Actions"

      - name: 🤖 Upload apk by bot
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-armeabi-v7a-release-signed.apk
          message: "🚀 Android arm-v7a Apk Build by Github Actions"

      - name: 🤖 Upload apk by bot
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          message: "🚀 Android arm64-v8a Apk Build by Github Actions"

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SECRET }}
          source: ./build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          target: /var/kite/web/apk/
          strip_components: 5

      - name: SSH Remote Rename apk
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SECRET }}
          script: |
            rm /var/kite/web/apk/sit-kite-arm64-v8a-release-latest.apk
            mv /var/kite/web/apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk /var/kite/web/apk/sit-kite-arm64-v8a-release-latest.apk


  # Send notification
  notification:
    runs-on: ubuntu-latest
    needs: [ upload ]
    if: |
      github.event_name != 'pull_request' &&
      github.repository == 'SIT-kite/kite-app' &&
      always()
    steps:

      - uses: technote-space/workflow-conclusion-action@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with: { length: 7 }

      - name: 🤖 Build Success Notification
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🎉 [KiteApp](https://github.com/SIT-kite/kite-app)  Build  *${{ env.WORKFLOW_CONCLUSION }}*

            Author: *${{ github.actor }}*

            Message: *${{ github.event.head_commit.message }}*

            Commit: [${{ env.SHA }}](https://github.com/${{ github.repository }}/commit/${{ env.SHA }})

            Branch: *${{ env.BRANCH_NAME }}*

      - name: 🤖 Build Fail Notification
        if: env.WORKFLOW_CONCLUSION != 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🔴 [KiteApp](https://github.com/SIT-kite/kite-app)  Build  *${{ env.WORKFLOW_CONCLUSION }}*

            Author: *${{ github.actor }}*

            Message: *${{ github.event.head_commit.message }}*

            Commit: [${{ env.SHA }}](https://github.com/${{ github.repository }}/commit/${{ env.SHA }})

            Branch: *${{ env.BRANCH_NAME }}*

      - name: 🤖 PR Merged Notification
        if: github.event.pull_request.merged == true && env.WORKFLOW_CONCLUSION == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🎉 [KiteApp](https://github.com/SIT-kite/kite-app)  PR [#${{github.event.number}}](https://github.com/SIT-kite/kite-app/pull/${{github.event.number}}) Merged!

            Author: *${{ github.actor }}*

            Message: *${{ github.event.pull_request.title }}*

            Branch: *${{ env.BRANCH_NAME }}*
